name: Publish package to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:


permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/python-pytest.yml
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
      - name: Build package
        run: python setup.py sdist bdist_wheel
      # upload artidact
      - uses: actions/upload-artifact@v3
        with:
          name: orm-build
          path: ./dist/

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest

    - uses: actions/download-artifact@v3
      with:
        name: orm-build
        path: ./dist

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

    # if triggered by release, then upload build files
    - name: Get release
      if: github.event_name == 'release'
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: NBTX/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} 
        targets: ./dist/*
