# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:



jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ORM_MYSQL_PORT: 3380
      ORM_MYSQL_USER: root1
      ORM_MYSQL_PASSWORD: root
      ORM_MYSQL_DATABASE: test
    steps:
    - uses: mirromutth/mysql-action@v1.1
      with:
        host port: ${{ env.ORM_MYSQL_PORT }}
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql version: '8.0'
        mysql database: ${{ env.ORM_MYSQL_DATABASE }}
        mysql root password: ${{ env.ORM_MYSQL_PASSWORD }}
        mysql user: ${{ env.ORM_MYSQL_USER }}
        mysql password: ${{ env.ORM_MYSQL_PASSWORD }}
        
    - uses: actions/checkout@v2
    - run: ls
    - name: build
      run: |
        pip install .
        pip list
    - name: Create tables
      run:  mysql --port=${{ env.ORM_MYSQL_PORT }} -u${{ env.ORM_MYSQL_USER }} -p${{ env.ORM_MYSQL_PASSWORD }} ${{ env.ORM_MYSQL_DATABASE }} < tests/create.sql
    - run: pip install pytest
    - run: pytest
      
