name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  test:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install wheel pytest
          pip install .
      - name: create Mysql DB for pytest
        run: |
          sudo service mysql start
          mysql -uroot -proot < ./tests/create.sql
      - name: Test with pytest
        run: |
          pytest
